### PR TITLE
Enhanced model generation + code cleanup

### PR DESCRIPTION
**Pull request by Cavitt**
+ Code cleanup.
+ Modules now only import needed `typeorm` decorators.
+ Removed column pluralization due to wrong column names being generated.
+ Fixed an issue where columns clashed w/ `BaseEntity` props. *(**save** -> **saveAttribute**)*
+ Added the class validators below to modules. *(use `-v false` to disable)*
  ```ts
  @IsOptional()
  @IsEmail()
  @IsString()
  @IsNumber()
  @IsIn()
  ```
+ Added the option to change indentation style. *(e.g. `-i tab`, `-i 2`, `-i 4`)*
+ Replaced handlebars w/ custom serialization.
  ```ts
  private serializeEntity(entity) {
        this.typeormImports = {BaseEntity: true, Entity: true};
        this.validateImports = {};
        entity.relationImports();

        const tableName = entity.EntityName;
        const className = this.convertCase(tableName, this.Options.convertCaseEntity);
        const eol = this.getEOL();
        let content = '';

        content += this.flatten(entity.UniqueImports, this.serializeEntityImports);
        content += `${eol}@Entity('${tableName}')${eol}`;
        content += this.flatten(entity.Indexes, this.serializeIndexes);
        content += `export class ${className} extends BaseEntity {${eol}${eol}`;
        content += this.flatten(entity.Columns, this.serializeColumn);
        content += `}${eol}`;

        return `${this.serializeImports()}${content}`;
  }
  ```
+ Improved console message.
  ```
  [02:26:52] Creating model classes...
  [02:26:52] Done. Created 39 TypeORM model classes.
  ```
+ Improved module formatting. *(below generated w/ default settings, no modifications)*
  ```ts
  import {BaseEntity, Entity, Index, PrimaryGeneratedColumn, Column, OneToMany, OneToOne} from 'typeorm';
  import {IsNumber, IsOptional, IsString, IsEmail, IsIn} from 'class-validator';
  import {AccountBanHistory} from './AccountBanHistory';
  import {AccountBans} from './AccountBans';
  import {AccountViplist} from './AccountViplist';
  import {Players} from './Players';

  @Entity('accounts')
  @Index(['name'], {unique:true})
  @Index(['sessionkey'])
  export class Accounts extends BaseEntity {

    @PrimaryGeneratedColumn()
    @IsNumber()
    public id: number;

    @Column({length:254, nullable:true})
    @IsOptional()
    @IsString()
    public username?: string | null;

    @Column({length:32})
    @IsString()
    public name: string;

    @Column({type:'char', length:64})
    @IsString()
    public password: string;

    @Column({length:254})
    @IsEmail()
    public email: string;

    @Column({type:'enum', enum:["en","es","de","se","pt","pl"], nullable:true})
    @IsOptional()
    @IsIn(["en","es","de","se","pt","pl"])
    public language?: string[] | null;

    @Column({type:'char', length:30})
    @IsString()
    public sessionkey: string;

    @Column({type:'tinyint'})
    @IsNumber()
    public stayloggedinforsession: number;

    @Column({type:'char', length:16, nullable:true})
    @IsOptional()
    @IsString()
    public authsecret?: string | null;

    @Column({type:'char', length:2, nullable:true})
    @IsOptional()
    @IsString()
    public country?: string | null;

    @Column()
    @OneToMany(t=>AccountBanHistory, r=>r.accountId)
    public accountBanHistory: AccountBanHistory[];

    @Column()
    @OneToOne(t=>AccountBans, r=>r.accountId)
    public accountBans: AccountBans;

    @Column()
    @OneToOne(t=>AccountViplist, r=>r.accountId)
    public accountViplist: AccountViplist;

    @Column()
    @OneToMany(t=>Players, r=>r.accountId)
    public players: Players[];

  }
  ```

### CODE REVIEW

**Comment by Kononnable** [comment]
I thought I commented this PR earlier, but I guess I forgot. Sorry.

- Tests are failing.
- Some strings use quotation marks other use apostrophes.

**Comment by afurculita** [comment]
@Cavitt great job. Any news on this PR? :)

**Comment by Cavitt** [comment]
I haven't had time due to personal reasons. I will finish the PR in the coming weekends. Sorry guys!

**Comment by Cavitt** [comment]
@afurculita That would be much appreciated. All the features are complete, just needs tests fixed and formatting.

**Comment by Kononnable** [comment]
Closing PR as there were no changes for a long time. Codebase changed a lot since then so it would be hard to merge it.

I plan to go back to some features/changes introduced here in the future, but I won't have time to do it in the near future.

**Pull request closed without merging**
