### PR TITLE
Add --case option to create Angular-friendly entities and files

### PR DESCRIPTION
**Pull request by miltonhowe**
I added a -c option to generate model using
- PascalCase for entities
- camelCase for properties
- kebab-case for filenames

I refactored the _imports_ section to facilitate using the optional casing using Handlebars helpers.
I cleaned up the formatting in the template to remove some whitespace.

### CODE REVIEW

**Comment by travisbloom** [comment]
was there a reason this didnt get merged?

**Comment by Kononnable** [comment]
PR was closed by author before I had time to review it. I don't know why. 
I guess I didn't spend much time on closed PR thinking that @miltonhowe decided to introduce some more changes before PR.

**Comment by travisbloom** [comment]
@Kononnable if I reopened would you be oppose to merging?

**Comment by Kononnable** [comment]
I think different name styling options could be useful to some folks. As long as it doesn't break model generation(db schema made by generated model must be same as schema from which that model was generated) I don't see an argument to not include such changes in the project.

**Pull request closed without merging**
