### PR TITLE
MySQL bit support

### PR DESCRIPTION
**Pull request by rmachado**

### CODE REVIEW

**Comment by Kononnable** [comment]
Typeorm doesn't support bit type for mysql(https://github.com/typeorm/typeorm/blob/c654d5228ccdd867557cf0754e13d47cc2211186/src/driver/mysql/MysqlDriver.ts#L81). Even if you create model with bit type, there will be error like this one in the runtime `DataTypeNotSupportedError: Data type "bit" in "PostAuthor.Column_2" is not supported by "mysql" database.`

PR can be merged after typeorm adds bit type to supported values for mysql driver, otherwise it wouldn't generate valid model.

**Comment by RevealedFrom** [comment]
Is this feature in 0.2.9?

**Comment by RevealedFrom** [comment]
Is this feature in 0.2.9?

**Comment by Maia-Everett** [comment]
TypeORM now supports the `bit` type. The patch can be merged.

**Pull request merged**
