### PR TITLE
Support MSSQL named instances

### PR DESCRIPTION
**Pull request by Ricki-BumbleDev**
Addresses #264

### CODE REVIEW

**Comment by Kononnable** [comment]
Sorry for delay, I haven't spent much time on this project lately.
I didn't use mssql for a while now, but as I recall with named instance there is no need for port number. Names were used to replace port numbers.
Am I correct or is port number required when connecting to named instance(e.g. points to service which translates instance names to correct ip addresses/ports)?

**Comment by Ricki-BumbleDev** [comment]
Hey, no worries, we all are busy.

> Am I correct or is port number required when connecting to named instance(e.g. points to service which translates instance names to correct ip addresses/ports)?
AFAIK the latter is the case. The port is indeed for that service translating the instance name you mentioned. Default port is 1433, but I'm sure that could be changed.

**Comment by Kononnable** [comment]
Looked through the docs for `instanceName`: 
`The instance name to connect to. The SQL Server Browser service must be running on the database server, and UDP port 1444 on the database server must be reachable. (no default) Mutually exclusive with options.port.`
Didn't find any option for defining port to connect to SQL Server Browser, so it looks like it just ignores port value.

Moved asking for instance name and hided port selection if instance name is specified. Could you check if you can connect to named instance as expected? I don't have any windows machine atm.
In any case, I'll merge this PR later this week. Thanks for your work.

**Comment by Ricki-BumbleDev** [comment]
LGTM, still works

**Pull request merged**
